### ISSUE TITLE
Assess the FAIRness of the LOFAR LTA (meta)data catalog

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#2]
- [x] Read the [FAIR paper](https://content.iospress.com/articles/information-services-and-use/isu824)

- [x] Check the [publications](http://www.astron.nl/radio-observatory/lofar-science/lofar-papers/lofar-papers) that reference LOFAR LTA (meta)data (e.g. in Suppl., PIDs?)

- [x] Make assessment of the LOFAR LTA data according to all FAIR Metrics are summarized in this [document (All.pdf)](https://github.com/FAIRMetrics/Metrics/). Score the metrics manually for the LOFAR data. 
Access points:
- [web front page](https://lta.lofar.eu/)
- [web service](https://lta-dbview.lofar.eu/DbView)

- [x] Prepare 2 slides on the FAIRness of the LOFAR LTA (see Fig.1 from the [FAIR paper](https://content.iospress.com/articles/information-services-and-use/isu824) )

**Comment by elboyran** [comment]
## LOFAR publications

Have gone through some of the [LOFAR publications](http://www.astron.nl/radio-observatory/lofar-science/lofar-papers/lofar-papers) from the ASTRON page. The numbering below is the same as the one on the publications page.

### Summary:
**No explicit reference to the LOFAR LTA was found. The data used in the papers were described usually in a Table using some meta-data such as Observation IDs, Date, Time, rarely Project IDs. LOFAR hardware paper from 2013 (see 10. below) is often referenced.**

### Details:

- 2011

1. [van Leeuwen at al](https://arxiv.org/pdf/0909.3212.pdf). No reference to data. Reference to [LOFAR Transients Key Project](www.transientskp.org) (docs, software, pubs).
2. [Stappers et al](https://arxiv.org/pdf/1104.1577.pdf). Paper refered to later about pulsar observing modes. No data IDs.
5. [Kazemi et al.](https://arxiv.org/pdf/1012.1722.pdf) No reference to existing data.  Explaining on how simulated and real observations are obtained.


- 2012

3. [Offringa et al](https://www.aanda.org/articles/aa/pdf/2012/03/aa18497-11.pdf). Baseline ID of Low-band antenna (LBA), Fig, 4 at page 4. Seems not enough to find the data.
9. [Buitink et al](http://www.astrophys-space-sci-trans.net/8/29/2012/astra-8-29-2012.pdf). Westerbork Synthesis Radio Telescope was used to collect data - description of how they were collected. Design on how to use LOFAR in the future. 

- 2013
5. [Sotomayor-Beltran et al](https://www.aanda.org/articles/aa/pdf/2013/04/aa20728-12.pdf). Summary of LOFAR observing campaigns table (Table 1, page 7): PSR (B-name): pulsar, Date, Duration, stations and observation IDs. 
10. [Van Haarlem et al](https://www.aanda.org/articles/aa/pdf/2013/08/aa20873-12.pdf). Key paper describing the LOFAR system, architecture, stations, software, modes and analysis pipelines etc. Many people later refer to it. 

- 2014
8. [Morosan at al.](https://www.aanda.org/articles/aa/pdf/2014/08/aa23936-14.pdf) Refers to 2013 10. Technical description (p.2-3) of the past (2013!) data used, but no PID!
20. [Bilous et al.](https://www.aanda.org/articles/aa/pdf/2014/12/aa24425-14.pdf) Refers to 2013 10. and 2011 2. Observation IDs (Fig 1, page 3).

- 2015
20. [van Diepen](https://www.sciencedirect.com/science/article/pii/S2213133715000621?via%3Dihub). Data processing pipeline for data from different telescopes. Free abstract only.
28. [Nelles et al](https://arxiv.org/pdf/1507.08932.pdf). LOFAR calibration -> data generation.
29. [Zaroubi et al](https://arxiv.org/pdf/1508.06652.pdf). Specific pulsar data obtained in 2012- paper referred to for the description of the data + short overview. No PIDs.

- 2016
7. [Marcote et al](https://arxiv.org/pdf/1512.03016.pdf). Table 1 (p. 4) summarizing the observations (LOFAR at the bottom of the table). Project code, date, etc.).
19. [Abbot et al.](http://iopscience.iop.org/article/10.3847/0067-0049/225/1/8/pdf) (supplement to a Letter). Reference to 2013 10. New data.

- 2017
9. [Clarke et al.](https://www.aanda.org/articles/aa/pdf/2017/05/aa30152-16.pdf) MSSS. LOFAR MSSS referred by a paper. Obtaining new data.
25.[ Hoang et al](https://arxiv.org/pdf/1706.09903.pdf). LOFAR HBA data- new observations. Reference to 2013 10. Table 1. on page 3 summary of the observation parameters: Observation IDs, Pointing centers, Date, N stations and other technical data.

- 2018
8. [Gurkanet et al.](https://arxiv.org/pdf/1801.02629.pdf) Sloan Digital Sky Survey [link](http://www.mpa-garching.mpg.de/SDSS/) to catalogue! But can't find specific data point identifiers.
10.  [Broderick et al.](https://arxiv.org/pdf/1802.03406.pdf) Table 1 (page 3) with meta data about generated observations: Run, date, IDs, etc. 
12. [Polzin et al](https://arxiv.org/pdf/1802.02594.pdf). LOFAR HBA data, pipelines. Table 1 (on page 3) with meta-data: Date, Project ID, ObsID, Duration etc.
13. [Micilli et al](https://arxiv.org/pdf/1802.03473.pdf). Table 1 (on p.3) with meta data for new data: center frequency, bandwidth, time-span.

**Comment by elboyran** [comment]
## FAIR Metrics

For the description of all metrics see [FAIR Metrics ALL](http://htmlpreview.github.io/?https://github.com/FAIRMetrics/Metrics/blob/master/ALL.html). For each metric, the formal description is given as a link from the metric ID. The Compliance of the LTA to each metric is according to me (not a FAIR expert).

| Metric  Identifier | Metric Name                        | _Presence_      | Note                                             |
|---------|----------|-------------------------------|-------------------------------------------------------|
| [FM-F1A](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_F1A.pdf) |  **Identifier Uniqueness**   |   _Yes/No?_  | A _human_ can access each RDB record via unique identifiers (URL, via the [web service](https://lta-dbview.lofar.eu/DbView)), but there is not a registered identifier scheme. An example of accessing a record via [URL](https://lta-dbview.lofar.eu/DbView?mode=object_view&class_str=Observation&object_id=068A642746D8756EE053C016A9C3DB57&project=LOFARSCHOOL). |
| [FM-F1B](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_F1B.pdf) |  **Identifier Persistence**   |    _No_  | Since there is no identifier scheme, there is also no policy on what to do it it becomes deprecated.    |
|[FM-F2](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_F2.pdf)| **Machine-readability of metadata**| _No_| The metadata are described in great detail in the [Measurement set description for LOFAR](https://www.astron.nl/lofarwiki/lib/exe/fetch.php?media=public:documents:ms2_description_for_lofar_v05.pdf), which is _humanly_ readable. On the [wiki page](https://www.astron.nl/lofarwiki/doku.php?id=public:lta_tricks) there are examples of how to use the AstroWise Python API. That is not _machine-readable_. Initial additions to the LTA [had no metadata](https://lta.lofar.eu/Lofar)!|
|[FM-F3](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_F3.pdf)| **Resource Identifier in Metadata**| _Yes?_| Parsing the data from their metadata is possible from the [DB-View service](https://lta-dbview.lofar.eu/DbView) for a _human_. An example of accessing a record with `object_id=068A642746D8756EE053C016A9C3DB57` from project LOFARSCHOOL via [URL](https://lta-dbview.lofar.eu/DbView?mode=object_view&class_str=Observation&object_id=068A642746D8756EE053C016A9C3DB57&project=LOFARSCHOOL). Are these the semantic metadata we want to initiate a search from? |
|[FM-F4](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_F4.pdf)| **Indexed in a searchable resource**| _true?_ | Google search by me using the query ``Lofar long term archive" returns as first hit the [web  interface](https://lta.lofar.eu/Lofar),  the [wiki](https://www.astron.nl/lofarwiki/doku.php?id=public:lta_howto) is hit 4 and 5 is the [ASTRON page](https://www.astron.nl/radio-observatory/system-capabilities/depth-technical-information/lofar-data-archive/lofar-data-arch) pointing to LTA. The the [web service- DB view ](https://lta-dbview.lofar.eu/DbView) link where the identifiers (which are not PIDs) are is not returned.|
|[FM-A1.1](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_A1.1.pdf)| **Access Protocol**| _Yes_ | HTTP GET https://lta-dbview.lofar.eu/DbView returns 200 OK.|
|[FM-A2](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_A2.pdf)| **Metadata Longevity**|_No?_| There is no formal metadata longevity plan. At the same time, the Long term archive has a permanent storage at Surf SARA.|
|[FM-I1 ](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_I1.pdf)| **Use a Knowledge Representation Language**| _No_| There is no URL to the specification of the (meta)data knowledge representation language.|
|[FM-I2](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_I2.pdf)| **Use FAIR Vocabularies**| _No?_| There is a [document](https://www.astron.nl/lofarwiki/lib/exe/fetch.php?media=public:documents:ms2_description_for_lofar_v05.pdf) describing in detail all meta-data. No vocabularies used.|
|[FM-I3](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_I3.pdf) | **Use Qualified References**| _No_| There are no ontologies or linked data nor link-sets representing part or all of the archive.|
|[FM-R1.1](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_R1.1.pdf)| **Accessible Usage License** | _Yes?_| A [document](https://www.astron.nl/lofarwiki/doku.php?id=public:guap) containing the user access information.|
|[FM-R1.2](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_R1.2.pdf)| **Detailed provenance**| _No?_| There is provenance in the RDB of the LTA (meta)data, but there are no IRI1 (recognized citation provenance standard) and 2 as described in the metric document.|
|[FM-R1.3](https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_R1.3.pdf)| **Meets Community Standards**| _No_ | There is no electronic signature coming from a community authority.|

**Comment by elboyran** [comment]
FAIRNess slides are at [OneDrive](https://nlesc-my.sharepoint.com/:p:/g/personal/e_ranguelova_esciencecenter_nl/EdYYCkP7ablDpG6XSkDYyzkBWsraOr-HXwtfXG91m5GGyg?e=ab9BFg)
