### ISSUE TITLE
Expose the LOFAR (meta)data using the FAIR Data Point

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#4]
- [x] Clone  [ODEX-FAIRDataPoint](https://github.com/NLeSC/ODEX-FAIRDataPoint) to a lofar branch

- [x] Edit \python\config.ini

- [x] commit & push the branch [lofar](https://github.com/NLeSC/ODEX-FAIRDataPoint/tree/lofar)

- [x] deploy FDP with modified `config.ini`

**Comment by felipeZ** [comment]
The original FDP `config.ini` was modified and uploaded [here](https://github.com/EOSC-LOFAR/fair_data_point_infra/blob/master/config.ini).
